# Generated by Django 3.2.13 on 2023-06-22 11:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название соревнований')),
                ('describe', models.TextField(blank=True, verbose_name='Описание')),
                ('data', models.DateField(default=datetime.datetime(2023, 6, 22, 11, 11, 3, 404286, tzinfo=utc), verbose_name='Дата соревнований')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=16, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=32, verbose_name='Отчество')),
                ('data_or_birthday', models.DateField(verbose_name='Дата Рождения')),
                ('phone_number', models.CharField(max_length=45, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('sex', models.CharField(choices=[('мужской', 'мужской'), ('женский', 'женский')], max_length=7, verbose_name='Пол')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('describe', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Trener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=16, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=32, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=45, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Тренера',
                'verbose_name_plural': 'Тренер',
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime(2023, 6, 22, 11, 11, 3, 404610, tzinfo=utc), verbose_name='Время записи')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('competitionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.competition', verbose_name='Соревнования')),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Участник')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTrener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата заказа')),
                ('time', models.TimeField(verbose_name='Время заказа')),
                ('duration', models.TimeField(verbose_name='Продолжительность')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Заказчик')),
                ('trenerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.trener', verbose_name='Тренер')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата заказа')),
                ('time', models.TimeField(verbose_name='Время заказа')),
                ('duration', models.TimeField(verbose_name='Продолжительность')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer', verbose_name='Заказчик')),
                ('tableID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.table', verbose_name='Стол')),
            ],
        ),
    ]
