# Generated by Django 3.2.13 on 2023-06-22 11:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Стол', 'verbose_name_plural': 'Столы'},
        ),
        migrations.AlterField(
            model_name='competition',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 6, 22, 11, 15, 46, 464178, tzinfo=utc), verbose_name='Дата соревнований'),
        ),
        migrations.AlterField(
            model_name='registrationcompetition',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 11, 15, 46, 464507, tzinfo=utc), verbose_name='Время записи'),
        ),
        migrations.AlterField(
            model_name='table',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
