# Generated by Django 3.2.13 on 2023-06-23 12:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230622_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codeemail',
            options={'verbose_name': 'код активации через почту', 'verbose_name_plural': 'коды активации через почту'},
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name': 'Соревнование', 'verbose_name_plural': 'Соревнования'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Бронирование стола', 'verbose_name_plural': 'Бронирование стола'},
        ),
        migrations.AlterModelOptions(
            name='ordertrener',
            options={'verbose_name': 'Запись к тренеру', 'verbose_name_plural': 'Записи к тренерам'},
        ),
        migrations.AlterModelOptions(
            name='registrationcompetition',
            options={'verbose_name': 'Запись на соревнование', 'verbose_name_plural': 'Записи на соревнования'},
        ),
        migrations.AddField(
            model_name='trener',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 6, 23, 12, 33, 7, 181779, tzinfo=utc), verbose_name='Дата соревнований'),
        ),
        migrations.AlterField(
            model_name='registrationcompetition',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 12, 33, 7, 182135, tzinfo=utc), verbose_name='Время записи'),
        ),
    ]
