# Generated by Django 3.2.13 on 2023-06-23 15:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230623_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='rating',
        ),
        migrations.AddField(
            model_name='registrationcompetition',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 6, 23, 15, 38, 9, 770093, tzinfo=utc), verbose_name='Дата соревнований'),
        ),
        migrations.AlterField(
            model_name='registrationcompetition',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 23, 15, 38, 9, 770451, tzinfo=utc), verbose_name='Время записи'),
        ),
    ]
