# Generated by Django 3.2.13 on 2023-06-27 12:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230623_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trenerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.trener', verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 6, 27, 12, 35, 26, 804572, tzinfo=utc), verbose_name='Дата соревнований'),
        ),
        migrations.AlterField(
            model_name='registrationcompetition',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 27, 12, 35, 26, 804902, tzinfo=utc), verbose_name='Время записи'),
        ),
    ]
