# Generated by Django 3.2.13 on 2023-07-09 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20230628_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['data'], 'verbose_name': 'Соревнование', 'verbose_name_plural': 'Соревнования'},
        ),
        migrations.AddField(
            model_name='trener',
            name='education',
            field=models.CharField(default='', max_length=32, verbose_name='Спортивныйразряд'),
        ),
        migrations.AddField(
            model_name='trener',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Можно ли забронировать'),
        ),
        migrations.AddField(
            model_name='trener',
            name='peculiarities',
            field=models.CharField(default='', max_length=32, verbose_name='Спортивныйразряд'),
        ),
        migrations.AddField(
            model_name='trener',
            name='sports_rank',
            field=models.CharField(default='', max_length=32, verbose_name='Спортивныйразряд'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='data',
            field=models.DateField(default=datetime.datetime(2023, 7, 9, 14, 10, 14, 628670, tzinfo=utc), verbose_name='Дата соревнований'),
        ),
        migrations.AlterField(
            model_name='registrationcompetition',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 14, 10, 14, 628965, tzinfo=utc), verbose_name='Время записи'),
        ),
        migrations.AlterField(
            model_name='trener',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость занятия (руб/час)'),
        ),
    ]
