# Generated by Django 3.2.13 on 2023-07-10 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20230709_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='KindPriceListElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название типа элемента прайс-листа')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'тип элементов прайс-листа',
                'verbose_name_plural': 'типы элементов прайс-листа',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='', verbose_name='Фотография')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата фотографии')),
            ],
            options={
                'verbose_name': 'Фотографию',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('Абонемент', 'Абонемент'), ('Турнир', 'Турнир'), ('Аренда стола', 'Аренда стола'), ('Занятия', 'Занятия')], max_length=32, verbose_name='Тип элемента прайс-листа')),
                ('item_name', models.CharField(max_length=255, verbose_name='Название элемента')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('duration', models.DurationField(verbose_name='Продолжительность')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Прайс-лист',
            },
        ),
        migrations.AlterField(
            model_name='competition',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата соревнований'),
        ),
        migrations.AlterField(
            model_name='registrationcompetition',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время записи'),
        ),
        migrations.AlterField(
            model_name='trener',
            name='education',
            field=models.CharField(blank=True, default=' ', max_length=32, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='trener',
            name='peculiarities',
            field=models.CharField(blank=True, default=' ', max_length=32, null=True, verbose_name='Особенности'),
        ),
        migrations.AlterField(
            model_name='trener',
            name='sports_rank',
            field=models.CharField(blank=True, default=' ', max_length=32, null=True, verbose_name='Спортивныйр азряд'),
        ),
    ]
