# Generated by Django 3.2.13 on 2023-07-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20230710_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
