# Generated by Django 3.2.13 on 2023-07-11 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_pricelist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kindpricelistelement', verbose_name='Тип элемента прайс-листа'),
        ),
    ]
