# Generated by Django 3.2.13 on 2023-07-11 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_pricelist_item_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='item_type',
        ),
        migrations.AddField(
            model_name='pricelist',
            name='new_item_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.kindpricelistelement', verbose_name='Тип элемента прайс-листа'),
            preserve_default=False,
        ),
    ]
