# Generated by Django 3.2.13 on 2023-07-11 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20230711_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricelist',
            old_name='new_item_type',
            new_name='item_type',
        ),
    ]
