# Generated by Django 3.2.13 on 2023-07-16 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_registrationcompetition_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationcompetition',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время записи'),
        ),
    ]
