# Generated by Django 3.2.13 on 2023-07-17 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(choices=[(datetime.date(2023, 7, 17), datetime.date(2023, 7, 17)), (datetime.date(2023, 7, 18), datetime.date(2023, 7, 18)), (datetime.date(2023, 7, 19), datetime.date(2023, 7, 19))], verbose_name='Дата заказа'),
        ),
    ]
