# Generated by Django 3.2.13 on 2023-11-26 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_servise'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AbonementСustomer',
            new_name='CustomAbon',
        ),
    ]
