# Generated by Django 3.2.13 on 2023-12-10 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_rename_abonementсustomer_customabon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='duration',
            field=models.TimeField(choices=[(datetime.time(1, 0), '01:00'), (datetime.time(1, 30), '01:30')], verbose_name='Продолжительность'),
        ),
    ]
