# Generated by Django 3.2.13 on 2023-12-10 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_order_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='duration',
            field=models.TimeField(choices=[(datetime.time(1, 0), '01:-1'), (datetime.time(1, 30), '01:29'), (datetime.time(2, 0), '02:-1')], verbose_name='Продолжительность'),
        ),
    ]
