# Generated by Django 3.2.13 on 2023-12-22 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
